name: Output Details
on: push
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "The event that triggered this action was ${{ toJSON(github) }}"
      - name: Issues
        run: echo "The issue that triggered this action was ${{ toJSON(github.event.issue) }}"
